// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rwaAPI.Data;

namespace rwaAPI.Migrations
{
    [DbContext(typeof(rwaAPIContext))]
    [Migration("20220717075547_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("rwaAPI.Data.Models.owners", b =>
                {
                    b.Property<int>("ownerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adderess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("flatno")
                        .HasColumnType("int");

                    b.Property<int>("isparkingspace")
                        .HasColumnType("int");

                    b.Property<string>("noofmembers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("noofvechicles")
                        .HasColumnType("int");

                    b.Property<string>("officeaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ownername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("towerid")
                        .HasColumnType("int");

                    b.HasKey("ownerid");

                    b.ToTable("owners");
                });

            modelBuilder.Entity("rwaAPI.Data.Models.towers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("noflats")
                        .HasColumnType("int");

                    b.Property<int>("nofloors")
                        .HasColumnType("int");

                    b.Property<int>("phone")
                        .HasColumnType("int");

                    b.Property<string>("towerno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("towers");
                });
#pragma warning restore 612, 618
        }
    }
}
